# Generated by Django 4.0.1 on 2022-03-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginApp', '0004_userdb_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilePageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.CharField(default='bg_logo.jpg', max_length=500)),
                ('userDBmodeldata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginApp.userdb')),
            ],
        ),
    ]
