# Generated by Django 4.0.1 on 2022-03-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='rollnumber',
            field=models.IntegerField(default=0),
        ),
    ]
