# Generated by Django 4.0.1 on 2022-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_querystore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='category',
            field=models.CharField(default='S', max_length=1),
            preserve_default=False,
        ),
    ]
